# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
A = np.array([0,1,2,3,4,5,6,7,8,9])
B = np.reshape(A, (2, -1))
B

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
a=np.array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
a=np.array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
           [10,11,12,13,14]])
a.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
a = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
a.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
x = np.random.random((5,5))
np.square(x)

array([[0.679494  , 0.43086022, 0.32134336, 0.71142903, 0.04353795],
       [0.47979148, 0.15346423, 0.45609108, 0.92879778, 0.02681843],
       [0.84863138, 0.98433782, 0.08212933, 0.00666919, 0.10727993],
       [0.78697536, 0.27611172, 0.49090474, 0.01601839, 0.36266798],
       [0.38608174, 0.00224008, 0.05663319, 0.38271035, 0.83211028]])

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
x = np.random.random((5,6))
np.mean(x)

0.4964171804284524

## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
x = np.random.random((5,6))
np.std(x)

0.2898866488890524

## Question:10

### Find the median of the previous array in Q8?

In [10]:
x = np.random.random((5,6))
np.median(x)

0.6267158061507025

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
x = np.random.random((5,6))
x.T

array([[0.97332894, 0.87737489, 0.53451475, 0.38415287, 0.52392623],
       [0.86197462, 0.51864378, 0.90064567, 0.64640792, 0.62554169],
       [0.07555644, 0.28734284, 0.84571186, 0.79116009, 0.4893041 ],
       [0.69774712, 0.86622092, 0.87748071, 0.14263925, 0.44946953],
       [0.57266787, 0.91082449, 0.98587464, 0.85311392, 0.49769927],
       [0.42780389, 0.07019449, 0.11001224, 0.50893956, 0.75897377]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
n_array = np.array([[55, 25, 15, 41], 
                    [30, 44, 2, 54], 
                    [11, 45, 77, 11], 
                    [11, 212, 4, 20]]) 
trace = np.trace(n_array)
trace

196

## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
print(np.linalg.det(n_array))

-25166735.999999996


## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
a = np.array([[10, 7, 4], [3, 2, 1]])
print(np.percentile(a, 5))
print(np.percentile(a, 95))

1.25
9.25


## Question:15

### How to find if a given array has any null values?

In [18]:
a = np.array([[10, 7, 4], [3, 2, 3]])
np.isnan(a)

array([[False, False, False],
       [False, False, False]])